chore: Switch to Node.js 22 for building release
Version 24 gave the following

warning svelte-eslint-parser@1.8.0: The engine "pnpm" appears to be invalid.
error i18next-parser@9.1.0: The engine "node" is incompatible with this module. Expected version "^18.0.0 || ^20.0.0 || ^22.0.0". Got "24.16.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.

See https://github.com/obsidian-tasks-group/obsidian-tasks/actions/runs/27370470819/job/80881088689