chore(deps-dev): bump typescript from 4.7.4 to 5.0.4
And fully update other typescript dependencies.
See the diffs in package.json for details of other package version changes.

This replaces dependabot PR #1843.

Also temporarily added the following to compilerOptions:

"ignoreDeprecations": "5.0"

in order to silence these messages:

error TS5101: Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.

error TS5101: Option 'preserveValueImports' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.