chore: Fix error TS5055: Cannot write file ...tests/global-setup.js
Make tsc put any generated files in generated/ directory, which is now git-ignored.