chore: Fix error message from newer svelte dependencies. (#2119)
The error message was:

Error: Argument of type '{ "bind:value": string; id: string; type: string; class: string; placeholder: string; accesskey: string | null; "on:keydown": (e: KeyboardEvent) => void; "on:paste": () => void; "on:drop": () => void; }' is not assignable to parameter of type 'HTMLProps<"textarea", HTMLAttributes<any>>'.
  Object literal may only specify known properties, and '"type"' does not exist in type 'HTMLProps<"textarea", HTMLAttributes<any>>'. (ts)
                id="description"
                type="text"
                class="tasks-modal-description"

They are complaining about the 'type="text"' line.

When I delete that line and test the Create or edit task modal,
the Description field still works fine.

I believe that this line was a hangover from an earlier version of this
code where the Description field was a one-line field.